### ISSUE TITLE
Fails to build on non-glibc systems

### ISSUE THREAD

**Issue by jbeich** [moverest/wl-kbptr#5]
Regressed by 09beb1edf5f0. Removing the non-standard header makes it build again.

```c
$ cc --version
FreeBSD clang version 18.1.4 (https://github.com/llvm/llvm-project.git llvmorg-18.1.4-0-ge6c3289804a6)
Target: x86_64-unknown-freebsd15.0
Thread model: posix
InstalledDir: /usr/bin

$ meson setup _build
$ meson compile -C _build
[...]
src/main.c:10:10: fatal error: 'bits/getopt_core.h' file not found
   10 | #include <bits/getopt_core.h>
      |          ^~~~~~~~~~~~~~~~~~~~
```

**Comment by moverest** [comment]
What a pleasant surprise! I've never thought someone would try this program on FreeBSD. :sweat_smile: 

Please let me know if b29350c3cdb9813ccd79e15757455e1e6f7c1ade solves the issue.

**Comment by jbeich** [comment]
I confirm, builds fine now.
