### PR TITLE
Support building against OpenCV 4 or 5

### LINKED ISSUE #99: Build on OpenCV 5.0
Arch switched to OpenCV 5.0 and build failed.

Here's the small patch to build wl-kbptr 

[opencv5.patch](https://github.com/user-attachments/files/29748805/opencv5.patch)

### PR DESCRIPTION
**Pull request by DereckAn**
Fixes #99.

Arch switched to OpenCV 5 and `wl-kbptr` stopped building there with
`-Dopencv=enabled`. OpenCV 5 moved `cv::boundingRect` out of `imgproc.hpp`
into `opencv2/geometry/2d.hpp`, so the build fails first on the missing
`opencv4` pkg-config file, and then on `'boundingRect' is not a member of
'cv'` once you point it at OpenCV 5.

I saw the patch in #99, but it swaps `opencv4` for `opencv5` outright, and
Debian, Ubuntu and Fedora are all still on OpenCV 4. So this looks for
OpenCV 4 first and only falls back to 5, with the moved header guarded by
`__has_include`. If your build works today, nothing changes for you: same
dependency, and the new include gets skipped entirely.

I tested both sides. On my Arch machine (OpenCV 5.0.0, no opencv4 installed
at all) it resolves opencv5 and builds. In a Debian trixie container
(OpenCV 4.10, no opencv5) it resolves opencv4 and builds. Release build with
`-Dopencv=enabled` both times, `test_label` passes, and clang-format is happy.

I also wanted to check that OpenCV 5 wasn't just linking but actually
detecting the same things, so I called `compute_target_from_img_buffer()` on a
synthetic image with four rectangles in known positions. It returned all
four, each a couple of pixels bigger than what I drew, which is what the
dilate kernel should do.

One thing I haven't done is run `mode_floating.source=detect` against a real
screen on OpenCV 5. The change doesn't touch the screencopy path so I don't
expect trouble, but I didn't want to claim more than I actually checked.

Minor thing in case it comes up: OpenCV 5 moves `boundingRect` into a separate
`libopencv_geometry`, but `pkg-config --libs opencv5` already lists it, so
there's nothing to change on the link line.

### CODE REVIEW

**Comment by OfficialAbhinavSingh** [comment]
Independent confirmation on Arch, opencv 5.0.0-9, with no OpenCV 4 present on
the system. Built this branch (b75e542) with `-Dopencv=enabled`:

    Run-time dependency opencv4 found: NO  (tried pkg-config and cmake)
    Run-time dependency opencv5 found: YES 5.0.0
    [41/41] Linking target wl-kbptr

The resulting binary links the four `libopencv_*.so.500` and reports
`wl-kbptr 0.4.1 (opencv)`.

Worth noting I hit both failures separately and wrote the same two-part fix
before finding this PR, so the diagnosis holds up to independent rediscovery.
I'm running that equivalent patch as a local package rebuild; the toggle I use
runs `-o modes=tile,bisect,click` and works. I have not run `detect` mode
against a real screen on OpenCV 5, and I only built and `--version`'d this
exact branch rather than daily-driving it.

For impact: the current AUR `wl-kbptr 0.4.1-2` is a hard failure on Arch
today, not only a build-from-source issue. The prebuilt binary still links
against OpenCV 4, so it dies at exec:

    wl-kbptr: error while loading shared libraries: libopencv_imgproc.so.413:
    cannot open shared object file: No such file or directory

That reads as "the keybind does nothing" rather than as a dependency problem,
which is what sent me looking in the wrong place for a while.

**Comment by moverest** [comment]
The patch works as expected. Merged. Thank your for you contribution.

As for the binding not doing anything when the program fails to load, I'm not sure what the best solution would be. My first impression would be that it falls on the user to look at their logs if the binding doesn't work but I'm not set on that.
